version: "3.8"
services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./acme.json:/acme.json"
    labels:
      - "traefik.enable=true"
    environment:
      - TZ=UTC
    networks:
      - web
networks:
  web:
    external: true
